services:
  postgres:
    image: postgres:17
    container_name: track-pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

  nats:
    image: nats:2.12.4
    container_name: track-nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

  redis:
    image: redis:7
    container_name: track-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: track-s3
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./storage:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: curlimages/curl:8.12.1
    container_name: track-s3-init
    restart: "no"
    depends_on:
      - minio
    environment:
      BUCKET: tasktrackerfiles
      ENDPOINT: http://minio:9000
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
    volumes:
      - ./scripts/create_local_bucket.sh:/create_local_bucket_for_docker.sh:ro
    entrypoint: ["/bin/sh", "/create_local_bucket_for_docker.sh"]

volumes:
  pgdata:
  redisdata:
