// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddMemberEvent = { user_id: string, name: string, email: string, 
/**
 * Превью аватарки
 */
avatar: boolean, 
/**
 * Дата приглашения (вступления)
 */
member_since: string, workspace_id: string, };
