// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadRequestError } from "./BadRequestError";
import type { ValidationErrorNamed } from "./ValidationErrorNamed";

export type BadRequestErrorResponse = { "type": "Validation", "reason": Array<ValidationErrorNamed> } | { "type": "Other", "reason": BadRequestError };
