// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateStatusRequest } from "./CreateStatusRequest";
import type { CreateTagRequest } from "./CreateTagRequest";
import type { WorkspaceName } from "./WorkspaceName";

export type CreateWorkspaceRequest = { name: WorkspaceName, statuses: Array<CreateStatusRequest>, tags: Array<CreateTagRequest>, };
