// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorSchema } from "./ColorSchema";

export type CreateTagRequest = { name: string, color: ColorSchema, };
