// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorSchema } from "./ColorSchema";
import type { StatusCategorySchema } from "./StatusCategorySchema";

export type CreateStatusRequest = { name: string, category: StatusCategorySchema, color: ColorSchema, };
