// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForbiddenError } from "./ForbiddenError";

export type ForbiddenErrorResponse = { reason: ForbiddenError, };
