// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginResponse = { user_id: string, email: string, avatar_id: string | undefined, token: string, refresh_token: string, token_exp: string, refresh_exp: string, server_time: string, };
