// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginResponse = { 
/**
 * User id (uuid)
 */
user_id: string, name: string, email: string, avatar: string | null, avatar_preview: string | null, created_at: string, updated_at: string, deleted_at: string | null, 
/**
 * access token
 */
token: string, 
/**
 * refresh token
 */
refresh_token: string, 
/**
 * token expiration date
 */
token_exp: string, 
/**
 * refresh token expiration date
 */
refresh_exp: string, 
/**
 * server time for calculating time difference
 */
server_time: string, };
