// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefreshTokenResponse = { 
/**
 * access token
 */
token: string, 
/**
 * refresh token
 */
refresh_token: string, 
/**
 * token expiration date
 */
token_exp: string, 
/**
 * refresh token expiration date
 */
refresh_exp: string, 
/**
 * server time for calculating time difference
 */
server_time: string, };
