// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserName } from "./UserName";

export type RegisterRequest = { 
/**
 * User name (full)
 */
name: UserName, 
/**
 * User email
 */
email: string, 
/**
 * User password
 */
password: string, };
