// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterRequest = { 
/**
 * User name (full)
 */
name: string, 
/**
 * User email
 */
email: string, 
/**
 * User password
 */
password: string, };
