// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorSchema } from "./ColorSchema";
import type { StatusCategorySchema } from "./StatusCategorySchema";

export type StatusResponse = { id: string, name: string, category: StatusCategorySchema, color: ColorSchema, workspace: string, created_at: string, updated_at: string, deleted_at: string | null, };
