// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusCategorySchema = "task_difinition" | "work_waiting" | "work_in_progress" | "blocked" | "test_waiting" | "test_in_progress" | "done" | "canceled";
