// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorSchema } from "./ColorSchema";

export type TagResponse = { id: string, name: string, color: ColorSchema, workspace: string, created_at: string, updated_at: string, deleted_at: string | null, };
