// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnauthotizedError } from "./UnauthotizedError";

export type UnauthotizedErrorResponse = { reason: UnauthotizedError, };
