// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorSchema } from "./ColorSchema";
import type { TagName } from "./TagName";

export type UpdateTagRequest = { name: TagName | null, color: ColorSchema | null, };
