// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorSchema } from "./ColorSchema";
import type { StatusCategorySchema } from "./StatusCategorySchema";
import type { StatusName } from "./StatusName";

export type UpdateStatusRequest = { name: StatusName | null, category: StatusCategorySchema | null, color: ColorSchema | null, };
