// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserResponse = { id: string, name: string, email: string, avatar: string | null, avatar_preview: string | null, created_at: string, updated_at: string, deleted_at: string | null, };
