// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldValidationErrorKind } from "./FieldValidationErrorKind";

export type ValidationErrorKind = { "type": "Field", "kind": { field: string, kind: FieldValidationErrorKind, } } | { "type": "Body", "kind": string };
