// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValidationErrorKind = { "type": "MinLength", "value": number } | { "type": "MaxLength", "value": number } | { "type": "Length", "value": { min: number, max: number, } } | { "type": "Email" } | { "type": "Url" };
