// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationErrorKind } from "./ValidationErrorKind";

export type ValidationErrorNamed = { field: string, reason: ValidationErrorKind, };
