// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceMemberResponse = { id: string, name: string, email: string, 
/**
 * Превью аватарки
 */
avatar: boolean, 
/**
 * Дата приглашения (вступления)
 */
member_since: string, 
/**
 * Дата исключения (выхода)
 */
deleted_at: string | null, };
