// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceResponse = { id: string, name: string, admin: string, created_at: string, updated_at: string, deleted_at: string | null, };
