// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusResponse } from "./StatusResponse";
import type { TagResponse } from "./TagResponse";

export type WorkspaceWithStatusesAndTagsResponse = { id: string, name: string, admin: string, created_at: string, updated_at: string, deleted_at: string | null, statuses: Array<StatusResponse>, tags: Array<TagResponse>, };
