// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddMemberEvent } from "./AddMemberEvent";
import type { RemoveMemberEvent } from "./RemoveMemberEvent";
import type { UpdateUserEvent } from "./UpdateUserEvent";
import type { UserInviteEvent } from "./UserInviteEvent";

export type WsOutgoingMsg = { "event": "Ping", "data": null } | { "event": "Pong", "data": null } | { "event": "Connected", "data": null } | { "event": "BadAuth", "data": null } | { "event": "UnknownMessageErr", "data": string } | { "event": "UpdateUser", "data": UpdateUserEvent } | { "event": "UserInvite", "data": UserInviteEvent } | { "event": "AddMember", "data": AddMemberEvent } | { "event": "RemoveMember", "data": RemoveMemberEvent };
